prompt_order = [
    "username",
    "hostname",
    "kubernetes",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "hg_branch",
    "package",
    "dotnet",
    "golang",
    "java",
    "nodejs",
    "php",
    "python",
    "ruby",
    "rust",
    "terraform",
    "nix_shell",
    "conda",
    "memory_usage",
    "aws",
    "env_var",
    "cmd_duration",
    "jobs",
    "battery",
    "time",
    "line_break",
    "character",
]

[aws]
displayed_items = "profile"
prefix = ""
disabled = true

[hostname]
ssh_only = false
prefix = "⟪"
suffix = "⟫"
style = "bold dimmed green"

[time]
disabled = false
format = "[%T]"
